# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: "3.8"

services:
  commandapi:
    image: commandapi
    container_name: commandapi
    build:
      context: .
      dockerfile: src/CommandAPI/Dockerfile
    ports:
      - 80
